name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0268b1c90bcc79c0880729b5d46e3b0b5449b9f196326a4e738e77ca7c4c905b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
