name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ced777d8f6a691e428325da68764ebaac35f438f166ffe1aaaac40a53075aaca"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
