name = "The Transcontinental Co"
author = "kilaXphantom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b42344b70a65f7e758c4d92794d756e887d721946ca3beeaa9c85e5538dfdd7"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
