name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd599d1828b20ca29e2032761c48bd46290177157e49622e84d9c9a6abfb0edd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
