name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afbb2cd4e731c7e03c6a5be919592b575fa386b967cefe21df88a2abdc5345eb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
