name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c7d41518d47b914f4765d2da43aaa97be439b7526c20be37711cb0fdbc7216"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
