name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ed7b0a1fcb0dfb908251348151ebddd06cfdec862729cc75f77efb8a78f247d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
