name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd91fa9365b97b8fb7d383eb35063f55c1d4e74bb31f1d8b38f50ae87b218207"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
