name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03491b9eaba614ccead35d92ebe2d775ce616191fb100635cc98b45ca045e10a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
