name = "The Transcontinental Co"
author = "kilaXphantom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "669053faf3e3f0c4379903d2a55559191d90a5ba3fe0e44bdafcd5844415f026"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
