name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7034af221bde26db9c4332acdc3ce209652ceea93091036c84e679240bbf08ff"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
