name = "The Transcontinental Co"
author = "kilaXphantom"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a0cc686ffdedd525411246d7039b4e814fbe4ed56ac7d7d1b851aea2a18993"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
