name = "The Transcontinental Co"
author = "kilaXphantom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d52869ea555304869f8906ed07f5c4179bbc6b2e09fa70a01acc3167203e40f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
