# Don't change this! Version used to track needed updates.
version = 0
turnOffPotionParticles = "NONE"
reduceAllChance = 1.0
reduceDecreasedChance = 1.0
disableParticles = false
byTypeReductions = {  }